#!/usr/bin/env bash
version="6.8.12"
name="debian-linux-libc-dev"
depends=""
description="temel dağıtım kernel dosyası ve moduller"
source=""
groups="sys.base"
setup()
{
	echo ""
	# deb dosyası indirilir http://ftp.tr.debian.org/debian/pool/main/l/linux/
	cd $SOURCEDIR
	wget -O image.deb http://ftp.tr.debian.org/debian/pool/main/l/linux/linux-libc-dev_6.8.12-1_all.deb
	# ar x indirilen dosya
	ar x image.deb
	# tar -xf data.tar.xz
	tar -xf data.tar.xz
	# find ./ -iname "*" -exec unxz {} \; komutuyla xz açılır
	

	
}
build()
{
	echo ""
}
package()
{
	cd $BUILDDIR

	cp -prfv usr  ${DESTDIR}/
	mkdir -p $DESTDIR/usr/include
	mkdir -p $DESTDIR/usr/include/x86_64-linux-gnu
	mkdir -p $DESTDIR/usr/include/x86_64-linux-gnu/asm
	cd $DESTDIR/usr/include
	
	ln -s x86_64-linux-gnu/asm asm

	
}


