#!/bin/bash

    for level in boot default nonetwork shutdown sysinit ; do
        mkdir -p /etc/runlevels/$level
    done
    touch /etc/fstab
    
rc-update add eudev default
rc-update add hostname default
#rc-update add udhcpc default
